version: "2"
services:
  backend:
    image: bonnie-backend:latest
    container_name: "backend"
    ports:
      - 8082:8082
  frontend:
    image: bonnie-frontend:latest
    container_name: "frontend"
    ports:
      - 8081:80